# fly.toml app configuration file generated for flex-warranty-api on 2025-07-29T12:34:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flex-warranty-api'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
